name: Makefile CI

on:
  workflow_call:

  workflow_dispatch:

  push:
    branches:
      - main
      - 'release-\d.\d\d'

  pull_request:
    branches:
      - main
      - 'release-\d.\d\d'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash

    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run lint
        run: make lint

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Run ginkgo Dry Run
        run: ginkgo run -vv -r --dry-run ./tests/
        env:
          ECO_DRY_RUN: true
          WORKLOAD_IMAGE: registry.access.redhat.com/ubi9/ubi-minimal:latest

      - name: Run unit tests
        run: make test

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Dockerfile
        run: docker build -t system-tests:ci -f Dockerfile .
